<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'apptest' => '/AppTest.php',
                'configtest' => '/ConfigTest.php',
                'loggerfiletest' => '/modules/logger/custom_loggers/LoggerFileTest.php',
                'loggertest' => '/modules/logger/LoggerTest.php',
                'modulemanagertest' => '/core/ModuleManagerTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd