<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'pff\\acontroller' => '/core/AController.php',
                'pff\\amodel' => '/core/AModel.php',
                'pff\\amodule' => '/modules/AModule.php',
                'pff\\app' => '/App.php',
                'pff\\aview' => '/core/AView.php',
                'pff\\configexception' => '/exceptions/ConfigException.php',
                'pff\\pffexception' => '/exceptions/PffException.php',
                'pff\\pro' => '/exceptions/Pro.php',
                'pff\\routing' => '/core/Routing.php',
                'pff\\routingexception' => '/exceptions/RoutingException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd