<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'pff\\amodule' => '/modules/AModule.php',
                'pff\\app' => '/App.php',
                'pff\\configexception' => '/exceptions/ConfigException.php',
                'pff\\iroutingstrategy' => '/core/IRoutingStrategy.php',
                'pff\\pffexception' => '/exceptions/PffException.php',
                'pff\\routing' => '/core/Routing.php',
                'pff\\routingexception' => '/exceptions/RoutingException.php',
                'pff\\routingmvc' => '/core/RoutingMVC.php',
                'pff\\routingpage' => '/core/RoutingPage.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd