<?php

require_once '/home/stonedz/Documents/Work/pff/lib/App.php';

/**
 * Test class for App.
 * Generated by PHPUnit on 2012-03-04 at 11:37:03.
 */
class AppTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var App
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new App('one/two/three');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testSetErrorReporting().
     */
    /*public function testSetErrorReporting()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }*/

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testRemoveMagicQuotes().
     */
    /*public function testRemoveMagicQuotes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }*/

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testUnregisterGlobals().
     */
    /*public function testUnregisterGlobals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }*/

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testRun().
     */
    /*public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }*/

    /**
     */
    public function testAddRoute(){
        $this->object->addRoute('admin','Administrator');
        $this->assertArrayHasKey('admin', $this->object->getRoutes());
    }

    /**

     */
    public function testAddStaticRoute(){
        $this->object->addStaticRoute('admin','admin');
        $this->assertArrayHasKey('admin', $this->object->getStaticRoutes());
    }

    /**
     *
     *     */
    public function testSetUrl()
    {
        // Remove the following lines when you implement this test.
        $this->object->setUrl('test');
        $this->assertEquals('test', $this->object->getUrl());
    }

}
?>
